### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by fahdshaykh** [mdobydullah/laravel-spa-vue3-auth-crud#6]
logout is not working

**Comment by fahdshaykh** [comment]
the logout issue is fixed by replacing in api user controller from Session::flush(); to Auth::guard('web')->logout();

**Comment by mdobydullah** [comment]
> the logout issue is fixed by replacing in api user controller from Session::flush(); to Auth::guard('web')->logout();

Thanks for letting me know.
